FROM python:3.8-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
ENV FLASK_APP=reservation_service.py
CMD ["flask", "run", "--host=0.0.0.0", "--port=5003"]
